### ISSUE TITLE
Arch Linux pacman should use option --noconfirm

### ISSUE THREAD

**Issue by stardiviner** [jabranham/system-packages#14]
RT
original post: https://github.com/jwiegley/use-package/issues/587

**Comment by jabranham** [comment]
You're right that there should probably be some way of passing arguments to the package manager. I'll work on that.

**Comment by jabranham** [comment]
Setting `system-packages-noconfirm` to `t` should bypass user confirmation.

It currently only works on apt and pacman based systems, I have to look up how to do this with other package managers.

**Comment by stardiviner** [comment]
Thanks.
