### ISSUE TITLE
Change from `brew upgrade --all` to `brew upgrade`

### ISSUE THREAD

**Issue by ghost** [jabranham/system-packages#19]
- macOS Sierra version 10.12.6
- system-packages 20180131.1624 (melpa)
- GNU Emacs 25.3.1
- Homebrew 1.5.8 (git revision 5413b; last commit 2018-03-07)

Calling `system-packages-update` results in the following warning:

```
Warning: Calling 'brew upgrade --all' is deprecated!
Use 'brew upgrade' instead.
```

References:
https://github.com/Homebrew/brew/pull/1202

**Comment by mbroe** [comment]
https://github.com/Homebrew/brew/pull/1202

**Comment by jabranham** [comment]
Done, thanks!

**Comment by ghost** [comment]
Thank you!
