### ISSUE TITLE
Update README (setq system-packages-package-manager) instructions

### ISSUE THREAD

**Issue by ghost** [jabranham/system-packages#22]
If I set my package manager of choice in the way [the README suggests](https://github.com/jabranham/system-packages#adding-other-package-managers): 

```
(setq system-packages-package-manager "apt")
```

... then run `system-packages-update`, I get the following error:

```
update not supported in "apt"
```

If I instead set it like so:

```
(setq system-packages-package-manager 'apt)
```

... everything works as expected.

**Comment by jabranham** [comment]
Fixed, thanks!
