### ISSUE TITLE
Expose the functionality for retrieving a command.

### ISSUE THREAD

**Issue by akhramov** [jabranham/system-packages#25]
Hi,

First of all, thanks for your package. It's really helpful.

I would like to discuss the possibility of exposing command retrieving functionality. As it stands now, some integrations need to know which shell command is going to be executed. `use-package` integration is the most notable example:

https://github.com/jwiegley/use-package/blob/512aa50b025018cb8574498d868814f73c02bb9b/use-package-ensure-system-package.el#L30-L42

```elisp
(defun use-package-ensure-system-package-install-command (pack)
  "Return the default install command for PACK."
  (let ((command
         (cdr (assoc 'install (cdr (assoc system-packages-package-manager
                                          system-packages-supported-package-managers))))))
    (unless command
      (error (format "%S not supported in %S" 'install system-packages-package-manager)))
    (unless (listp command)
      (setq command (list command)))
    (when system-packages-use-sudo
      (setq command (mapcar (lambda (part) (concat "sudo " part)) command)))
    (setq command (mapconcat 'identity command " && "))
(mapconcat 'identity (list command pack) " ")))
```

This duplicates the code already existing in the package, but not exposed yet.
Would it make sense to expose this piece of functionality, so integrations would be able to leverage it? What do you think?

See also jwiegley/use-package#661

Thanks!

**Comment by jabranham** [comment]
I just pushed a commit that adds `system-packages-get-command`. Let me know if that's not what you were asking about.

@waymondo for the ping.

**Comment by akhramov** [comment]
Yeah, exactly. Thanks!

**Comment by akhramov** [comment]
@jabranham  also, may I ask you to make a release?

**Comment by jabranham** [comment]
Done

**Comment by akhramov** [comment]
Thank you very much!
